In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
data = pd.read_csv('AutoImmune\Autoimmune_Disorder_10k_with_All_Disorders.csv')
data

,Patient_ID,Age,Gender,Diagnosis,Sickness_Duration_Months,RBC_Count,Hemoglobin,Hematocrit,MCV,MCH,...,Anti_TIF1,Anti_epidermal_basement_membrane_IgA,Anti_OmpC,pANCA,Anti_tissue_transglutaminase,anti_Scl_70,Anti_Mi2,Anti_parietal_cell,Progesterone_antibodies,Anti_Sm
0,1,65,Female,Linear IgA disease,26,3.54,13.18,44.35,99.85,31.80,...,0,1,0,0,0,0,0,0,0,0
1,2,61,Male,Dermatomyositis,106,4.97,14.73,42.39,94.86,29.94,...,1,0,0,0,0,0,1,0,0,0
2,3,42,Male,Ord's thyroiditis,6,3.91,13.66,42.41,88.26,29.43,...,0,0,0,0,0,0,0,0,0,0
3,4,45,Female,Restless legs syndrome,11,4.57,14.96,40.10,85.95,27.42,...,0,0,0,0,0,0,0,0,0,0
4,5,78,Female,Autoimmune polyendocrine syndrome type 2 (APS2),30,4.88,11.21,37.58,93.16,29.87,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,12496,54,Male,Normal,0,4.51,17.17,42.46,94.95,27.96,...,0,0,0,0,0,0,0,0,0,0
12496,12497,29,Male,Normal,0,4.62,13.72,43.65,94.54,31.00,...,0,0,0,0,0,0,0,0,0,0
12497,12498,34,Male,Normal,0,4.95,15.37,41.78,84.67,30.94,...,0,0,0,0,0,0,0,0,0,0
12498,12499,80,Male,Normal,0,4.66,16.29,46.29,88.40,29.40,...,0,0,0,0,0,0,0,0,0,0
12499,12500,66,Male,Normal,0,5.09,16.65,46.63,81.99,27.96,...,0,0,0,0,0,0,0,0,0,0

In [5]:
data.isnull().sum()

Patient_ID                  0
Age                         0
Gender                      0
Diagnosis                   0
Sickness_Duration_Months    0
                           ..
anti_Scl_70                 0
Anti_Mi2                    0
Anti_parietal_cell          0
Progesterone_antibodies     0
Anti_Sm                     0
Length: 79, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 79 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Patient_ID                            12500 non-null  int64
 1   Age                                   12500 non-null  int64
 2   Gender                                12500 non-null  object
 3   Diagnosis                             12500 non-null  object
 4   Sickness_Duration_Months              12500 non-null  int64
 5   RBC_Count                             12500 non-null  float64
 6   Hemoglobin                            12500 non-null  float64
 7   Hematocrit                            12500 non-null  float64
 8   MCV                                   12500 non-null  float64
 9   MCH                                   12500 non-null  float64
 10  MCHC                                  12500 non-null  float64
 11  RDW                                   12500 non-null  float64
 12  Reticulocyte_Count                    12500 non-null  float64
 13  WBC_Count                             12500 non-null  int64
 14  Neutrophils                           12500 non-null  float64
 15  Lymphocytes                           12500 non-null  float64
 16  Monocytes                             12500 non-null  float64
 17  Eosinophils                           12500 non-null  float64
 18  Basophils                             12500 non-null  float64
 19  PLT_Count                             12500 non-null  int64
 20  MPV                                   12500 non-null  float64
 21  ANA                                   12500 non-null  int64
 22  Esbach                                12500 non-null  float64
 23  MBL_Level                             12500 non-null  float64
 24  ESR                                   12500 non-null  int64
 25  C3                                    12500 non-null  float64
 26  C4                                    12500 non-null  float64
 27  CRP                                   12500 non-null  float64
 28  Anti-dsDNA                            10000 non-null  float64
 29  Anti-Sm                               10000 non-null  float64
 30  Rheumatoid factor                     10000 non-null  float64
 31  ACPA                                  10000 non-null  float64
 32  Anti-TPO                              10000 non-null  float64
 33  Anti-Tg                               10000 non-null  float64
 34  Anti-SMA                              10000 non-null  float64
 35  Low-grade fever                       12500 non-null  int64
 36  Fatigue or chronic tiredness          12500 non-null  int64
 37  Dizziness                             12500 non-null  int64
 38  Weight loss                           12500 non-null  int64
 39  Rashes and skin lesions               12500 non-null  int64
 40  Stiffness in the joints               12500 non-null  int64
 41  Brittle hair or hair loss             12500 non-null  int64
 42  Dry eyes and/or mouth                 12500 non-null  int64
 43  General 'unwell' feeling              12500 non-null  int64
 44  Joint pain                            12500 non-null  int64
 45  Anti_dsDNA                            12500 non-null  int64
 46  Anti_enterocyte_antibodies            12500 non-null  int64
 47  anti_LKM1                             12500 non-null  int64
 48  Anti_RNP                              12500 non-null  int64
 49  ASCA                                  12500 non-null  int64
 50  Anti_Ro_SSA                           12500 non-null  int64
 51  Anti_CBir1                            12500 non-null  int64
 52  Anti_BP230                            12500 non-null  int64
 53  Anti_tTG                              12500 non-null  int64
 54  DGP                                   12500 non-null  int64
 55  Anti_BP180                            12500 non-null  int64
 56  ASMA                                  12500 non-null  int64
 57  Anti_IF                               12500 non-null  int64
 58  IgG_IgE_receptor                      12500 non-null  int64
 59  Anti_SRP                              12500 non-null  int64
 60  Anti_desmoglein_3                     12500 non-null  int64
 61  Anti_La_SSB                           12500 non-null  int64
 62  Anti_Jo1                              12500 non-null  int64
 63  ANCA                                  12500 non-null  int64
 64  anti_centromere                       12500 non-null  int64
 65  Anti_desmoglein_1                     12500 non-null  int64
 66  EMA                                   12500 non-null  int64
 67  Anti_type_VII_collagen                12500 non-null  int64
 68  C1_inhibitor                          12500 non-null  int64
 69  Anti_TIF1                             12500 non-null  int64
 70  Anti_epidermal_basement_membrane_IgA  12500 non-null  int64
 71  Anti_OmpC                             12500 non-null  int64
 72  pANCA                                 12500 non-null  int64
 73  Anti_tissue_transglutaminase          12500 non-null  int64
 74  anti_Scl_70                           12500 non-null  int64
 75  Anti_Mi2                              12500 non-null  int64
 76  Anti_parietal_cell                    12500 non-null  int64
 77  Progesterone_antibodies               12500 non-null  int64
 78  Anti_Sm                               12500 non-null  int64
dtypes: float64(26), int64(51), object(2)
memory usage: 7.5+ MB

In [7]:
data.describe()

,Patient_ID,Age,Sickness_Duration_Months,RBC_Count,Hemoglobin,Hematocrit,MCV,MCH,MCHC,RDW,...,Anti_TIF1,Anti_epidermal_basement_membrane_IgA,Anti_OmpC,pANCA,Anti_tissue_transglutaminase,anti_Scl_70,Anti_Mi2,Anti_parietal_cell,Progesterone_antibodies,Anti_Sm
count,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,...,12500.000000,12500.000000,12500.00000,12500.00000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000
mean,6250.500000,49.757040,47.964960,4.449722,13.124339,41.559422,90.175951,29.021782,33.605753,13.788202,...,0.014640,0.007040,0.00648,0.00624,0.014960,0.006160,0.014640,0.006800,0.006560,0.014800
std,3608.583517,17.740705,39.034342,0.572939,1.842016,3.318242,8.150511,1.628080,1.413444,1.175959,...,0.120112,0.083612,0.08024,0.07875,0.121398,0.078247,0.120112,0.082185,0.080731,0.120756
min,1.000000,18.000000,0.000000,3.500000,10.000000,36.000000,75.010000,26.000000,31.000000,11.500000,...,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3125.750000,34.000000,8.000000,3.980000,11.610000,38.880000,83.387500,27.690000,32.430000,12.800000,...,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6250.500000,50.000000,45.000000,4.460000,13.140000,41.540000,90.300000,29.030000,33.620000,13.730000,...,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9375.250000,65.000000,82.000000,4.830000,14.410000,43.810000,97.060000,30.382500,34.830000,14.720000,...,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,12500.000000,84.000000,119.000000,5.900000,17.500000,50.000000,105.000000,32.000000,36.000000,16.000000,...,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [9]:
X = data.drop(['Patient_ID', 'Diagnosis'], axis=1) 
y = data['Diagnosis']

In [10]:
X = pd.get_dummies(X, drop_first=True)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Using RandomForestClassifier

In [12]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [13]:
y_pred = model.predict(X_test)

In [14]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy Score:", acc)

Accuracy Score: 0.3416

In [15]:
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Classification Report:
                                                       precision    recall  f1-score   support

                Acute disseminated encephalomyelitis       0.00      0.00      0.00        17
                       Acute motor axonal neuropathy       0.00      0.00      0.00        16
                                   Addison's disease       0.00      0.00      0.00        16
                                     Alopecia areata       0.00      0.00      0.00        16
                     Anti-NMDA receptor encephalitis       0.00      0.00      0.00        16
                           Antiphospholipid syndrome       0.00      0.00      0.00        20
                               Autoimmune angioedema       1.00      1.00      1.00        16
                             Autoimmune encephalitis       0.00      0.00      0.00        17
                              Autoimmune enteropathy       1.00      1.00      1.00        16
                         Autoimmune hemolytic anemia       0.00      0.00      0.00        15
                                Autoimmune hepatitis       1.00      1.00      1.00        17
                               Autoimmune oophoritis       0.03      0.12      0.04        34
                                 Autoimmune orchitis       0.02      0.09      0.04        32
                             Autoimmune pancreatitis       0.00      0.00      0.00        15
     Autoimmune polyendocrine syndrome type 1 (APS1)       0.04      0.06      0.05        17
     Autoimmune polyendocrine syndrome type 2 (APS2)       0.00      0.00      0.00        16
     Autoimmune polyendocrine syndrome type 3 (APS3)       0.00      0.00      0.00        17
                  Autoimmune progesterone dermatitis       1.00      1.00      1.00        16
                              Autoimmune retinopathy       0.00      0.00      0.00        16
                                Autoimmune urticaria       1.00      1.00      1.00        19
                                  Autoimmune uveitis       0.00      0.00      0.00        15
                           Balo concentric sclerosis       0.00      0.00      0.00        17
                                    Behçet's disease       0.00      0.00      0.00        16
                          Bickerstaff's encephalitis       0.00      0.00      0.00        19
                                  Bullous pemphigoid       0.35      0.61      0.45        18
                                      Celiac disease       1.00      1.00      1.00        17
   Chronic inflammatory demyelinating polyneuropathy       0.00      0.00      0.00        20
                              Cicatricial pemphigoid       0.25      0.13      0.17        15
                                      Cogan syndrome       0.00      0.00      0.00        17
                                     Crohn's disease       1.00      1.00      1.00        16
                            Dermatitis herpetiformis       1.00      1.00      1.00        20
                                     Dermatomyositis       1.00      1.00      1.00        37
                            Diabetes mellitus type 1       0.00      0.00      0.00        15
                         Discoid lupus erythematosus       1.00      1.00      1.00        18
                                       Endometriosis       0.02      0.08      0.03        37
Eosinophilic granulomatosis with polyangiitis (EGPA)       0.00      0.00      0.00        15
                     Epidermolysis bullosa acquisita       1.00      1.00      1.00        18
                                    Erythema nodosum       0.00      0.00      0.00        17
                                        Fibromyalgia       0.00      0.00      0.00        17
                              Gestational pemphigoid       0.42      0.28      0.33        18
                                Giant cell arteritis       0.00      0.00      0.00        16
                                Goodpasture syndrome       0.00      0.00      0.00        16
              Granulomatosis with polyangiitis (GPA)       0.00      0.00      0.00        16
                                     Graves' disease       0.00      0.00      0.00        16
                              Graves' ophthalmopathy       0.12      0.06      0.08        17
                             Guillain-Barré syndrome       0.00      0.00      0.00        18
                          Hashimoto's encephalopathy       0.00      0.00      0.00        16
                             Hashimoto's thyroiditis       0.00      0.00      0.00        14
                            Hidradenitis suppurativa       0.12      0.15      0.13        20
      Idiopathic inflammatory demyelinating diseases       0.00      0.00      0.00        16
                       Idiopathic pulmonary fibrosis       0.00      0.00      0.00        14
                                     IgA nephropathy       0.05      0.05      0.05        19
                               IgA vasculitis (IgAV)       0.00      0.00      0.00        15
                             Immune thrombocytopenia       0.04      0.05      0.04        20
                             Inclusion body myositis       0.00      0.00      0.00        16
                                Intermediate uveitis       0.00      0.00      0.00        17
                               Interstitial cystitis       0.00      0.00      0.00        18
                           Interstitial lung disease       0.00      0.00      0.00        19
                              Interstitial nephritis       0.00      0.00      0.00        16
                                    Kawasaki disease       0.08      0.05      0.06        19
                   Lambert–Eaton myasthenic syndrome       0.00      0.00      0.00        16
                         Leukocytoclastic vasculitis       0.00      0.00      0.00        17
                                       Lichen planus       0.00      0.00      0.00        17
                                    Lichen sclerosus       0.00      0.00      0.00        14
                             Ligneous conjunctivitis       0.00      0.00      0.00        16
                                  Linear IgA disease       1.00      1.00      1.00        18
                                     Lupus nephritis       0.00      0.00      0.00        15
                                    Lupus vasculitis       0.00      0.00      0.00        17
                              Membranous nephropathy       0.05      0.06      0.06        17
                      Microscopic polyangiitis (MPA)       0.00      0.00      0.00        17
                                      Mooren's ulcer       0.04      0.05      0.05        19
                                             Morphea       0.00      0.00      0.00        20
                                  Multiple sclerosis       0.00      0.00      0.00        15
                                   Myasthenia gravis       0.00      0.00      0.00        30
                                            Myositis       0.00      0.00      0.00        17
                                Neuromyelitis optica       0.00      0.00      0.00        14
        Neuromyelitis optica (Devic's disease)/NMOSD       0.00      0.00      0.00        18
                                       Neuromyotonia       0.00      0.00      0.00        12
                                              Normal       1.00      1.00      1.00       500
                       Opsoclonus myoclonus syndrome       0.00      0.00      0.00        19
                                      Optic neuritis       0.00      0.00      0.00        16
                                   Ord's thyroiditis       0.00      0.00      0.00        16
              Paraneoplastic cerebellar degeneration       0.00      0.00      0.00        16
                 Paroxysmal nocturnal hemoglobinuria       0.00      0.00      0.00        15
                                  Pemphigus vulgaris       1.00      1.00      1.00        17
                                   Pernicious anemia       1.00      1.00      1.00        17
                          Polyarteritis nodosa (PAN)       0.00      0.00      0.00        13
                              Polymyalgia rheumatica       0.00      0.00      0.00        16
                                        Polymyositis       0.00      0.00      0.00        18
                           Premature ovarian failure       0.00      0.00      0.00        18
                      Primary sclerosing cholangitis       0.00      0.00      0.00        15
                                           Psoriasis       0.00      0.00      0.00        16
                      Pulmonary alveolar proteinosis       0.00      0.00      0.00        16
                              Restless legs syndrome       0.17      0.06      0.09        17
                             Rheumatic heart disease       0.00      0.00      0.00        13
                                Rheumatoid arthritis       0.00      0.00      0.00        18
                             Rheumatoid lung disease       0.00      0.00      0.00        16
                               Rheumatoid vasculitis       0.00      0.00      0.00        18
                                         Sarcoidosis       0.10      0.06      0.07        17
                                           Scleritis       0.00      0.00      0.00        18
                    Scleroderma (systemic sclerosis)       1.00      1.00      1.00        15
                                    Sjögren syndrome       0.00      0.00      0.00        17
                               Stiff-person syndrome       0.00      0.00      0.00        16
                                    Susac's syndrome       0.00      0.00      0.00        16
                                   Sydenham's chorea       0.00      0.00      0.00        14
                              Sympathetic ophthalmia       0.00      0.00      0.00        15
                        Systemic Lupus Erythematosus       1.00      1.00      1.00        19
                                Takayasu's arteritis       0.00      0.00      0.00        15
                 Thrombotic thrombocytopenic purpura       0.00      0.00      0.00        17
                                Tolosa–Hunt syndrome       0.00      0.00      0.00        16
                                 Transverse myelitis       0.00      0.00      0.00        18
                                  Ulcerative colitis       1.00      1.00      1.00        16
   Undifferentiated connective tissue disease (UCTD)       0.10      0.07      0.08        15
                               Urticarial vasculitis       0.00      0.00      0.00        15
                                          Vasculitis       0.00      0.00      0.00        20
                                            Vitiligo       0.09      0.06      0.07        18

                                            accuracy                           0.34      2500
                                           macro avg       0.17      0.17      0.17      2500
                                        weighted avg       0.34      0.34      0.34      2500

In [21]:
# Number of test samples
n_samples = X_test.shape[0]

# Get all unique classes from all client models
classes_ = np.unique(np.concatenate([model.classes_ for model in client_models]))

# Number of classes
n_classes = len(classes_)

# Initialize averaged probability matrix
avg_proba = np.zeros((n_samples, n_classes))

In [17]:
import numpy as np

n_clients = 5

# Convert to numpy if using pandas
X = np.array(X)
y = np.array(y)

# Shuffle dataset
indices = np.arange(len(X))
np.random.shuffle(indices)

X = X[indices]
y = y[indices]

# Split into 5 clients
clients_X = np.array_split(X, n_clients)
clients_y = np.array_split(y, n_clients)

print("Clients created successfully!")
print("Number of clients:", len(clients_X))

Clients created successfully!
Number of clients: 5

# Using Federated Learning

In [18]:
n_clients = 5
client_models = []
client_val_scores = []

for client_idx in range(n_clients):
    X_client_train, X_client_val, y_client_train, y_client_val = train_test_split(
        clients_X[client_idx], clients_y[client_idx],
        test_size=0.2, random_state=42,
        stratify=clients_y[client_idx])
    
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=8,
        class_weight='balanced',
        random_state=42 + client_idx
    )
    model.fit(X_client_train, y_client_train)
    client_models.append(model)
    
    val_acc = model.score(X_client_val, y_client_val)
    client_val_scores.append(val_acc)
    print(f"Client {client_idx+1} - Validation Accuracy: {val_acc:.4f}")

Client 1 - Validation Accuracy: 0.3420
Client 2 - Validation Accuracy: 0.3600
Client 3 - Validation Accuracy: 0.3500
Client 4 - Validation Accuracy: 0.3200
Client 5 - Validation Accuracy: 0.3320

In [19]:
client_weights = np.array(client_val_scores) / np.sum(client_val_scores)
print(f"\nClient weights: {client_weights}")

Client weights: [0.20070423 0.21126761 0.20539906 0.18779343 0.19483568]

In [22]:
for i, model in enumerate(client_models):
    proba = model.predict_proba(X_test)
    full_proba = np.zeros((n_samples, n_classes))
    
    for j, cls in enumerate(model.classes_):
        idx = np.where(classes_ == cls)[0][0]
        full_proba[:, idx] = proba[:, j]
    
    avg_proba += client_weights[i] * full_proba

y_pred_federated = classes_[np.argmax(avg_proba, axis=1)]

c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [26]:
acc = accuracy_score(y_test, y_pred_federated)
print(f"\nFederated Averaging Random Forest Accuracy: {acc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred_federated))

Federated Averaging Random Forest Accuracy: 0.3620

Classification Report:
                                                      precision    recall  f1-score   support

                Acute disseminated encephalomyelitis       0.50      0.06      0.11        17
                       Acute motor axonal neuropathy       0.07      0.06      0.06        16
                                   Addison's disease       0.12      0.06      0.08        16
                                     Alopecia areata       0.00      0.00      0.00        16
                     Anti-NMDA receptor encephalitis       0.00      0.00      0.00        16
                           Antiphospholipid syndrome       0.00      0.00      0.00        20
                               Autoimmune angioedema       1.00      1.00      1.00        16
                             Autoimmune encephalitis       0.04      0.06      0.05        17
                              Autoimmune enteropathy       1.00      1.00      1.00        16
                         Autoimmune hemolytic anemia       0.01      0.47      0.03        15
                                Autoimmune hepatitis       1.00      1.00      1.00        17
                               Autoimmune oophoritis       0.00      0.00      0.00        34
                                 Autoimmune orchitis       0.00      0.00      0.00        32
                             Autoimmune pancreatitis       0.12      0.07      0.09        15
     Autoimmune polyendocrine syndrome type 1 (APS1)       0.05      0.06      0.05        17
     Autoimmune polyendocrine syndrome type 2 (APS2)       0.00      0.00      0.00        16
     Autoimmune polyendocrine syndrome type 3 (APS3)       0.14      0.06      0.08        17
                  Autoimmune progesterone dermatitis       1.00      1.00      1.00        16
                              Autoimmune retinopathy       0.00      0.00      0.00        16
                                Autoimmune urticaria       1.00      1.00      1.00        19
                                  Autoimmune uveitis       0.00      0.00      0.00        15
                           Balo concentric sclerosis       0.00      0.00      0.00        17
                                    Behçet's disease       0.25      0.12      0.17        16
                          Bickerstaff's encephalitis       0.00      0.00      0.00        19
                                  Bullous pemphigoid       0.68      0.94      0.79        18
                                      Celiac disease       1.00      1.00      1.00        17
   Chronic inflammatory demyelinating polyneuropathy       0.29      0.10      0.15        20
                              Cicatricial pemphigoid       0.70      0.47      0.56        15
                                      Cogan syndrome       0.00      0.00      0.00        17
                                     Crohn's disease       1.00      1.00      1.00        16
                            Dermatitis herpetiformis       1.00      1.00      1.00        20
                                     Dermatomyositis       1.00      1.00      1.00        37
                            Diabetes mellitus type 1       0.00      0.00      0.00        15
                         Discoid lupus erythematosus       1.00      1.00      1.00        18
                                       Endometriosis       0.00      0.00      0.00        37
Eosinophilic granulomatosis with polyangiitis (EGPA)       0.04      0.07      0.05        15
                     Epidermolysis bullosa acquisita       1.00      1.00      1.00        18
                                    Erythema nodosum       0.01      0.24      0.02        17
                                        Fibromyalgia       0.14      0.06      0.08        17
                              Gestational pemphigoid       0.75      0.67      0.71        18
                                Giant cell arteritis       1.00      0.06      0.12        16
                                Goodpasture syndrome       0.00      0.00      0.00        16
              Granulomatosis with polyangiitis (GPA)       0.12      0.19      0.15        16
                                     Graves' disease       0.00      0.00      0.00        16
                              Graves' ophthalmopathy       0.12      0.06      0.08        17
                             Guillain-Barré syndrome       0.00      0.00      0.00        18
                          Hashimoto's encephalopathy       0.20      0.06      0.10        16
                             Hashimoto's thyroiditis       0.14      0.07      0.10        14
                            Hidradenitis suppurativa       0.07      0.05      0.06        20
      Idiopathic inflammatory demyelinating diseases       0.00      0.00      0.00        16
                       Idiopathic pulmonary fibrosis       0.00      0.00      0.00        14
                                     IgA nephropathy       0.07      0.16      0.10        19
                               IgA vasculitis (IgAV)       0.00      0.00      0.00        15
                             Immune thrombocytopenia       0.00      0.00      0.00        20
                             Inclusion body myositis       0.00      0.00      0.00        16
                                Intermediate uveitis       0.30      0.18      0.22        17
                               Interstitial cystitis       0.09      0.06      0.07        18
                           Interstitial lung disease       0.00      0.00      0.00        19
                              Interstitial nephritis       0.00      0.00      0.00        16
                                    Kawasaki disease       0.00      0.00      0.00        19
                   Lambert–Eaton myasthenic syndrome       0.00      0.00      0.00        16
                         Leukocytoclastic vasculitis       0.00      0.00      0.00        17
                                       Lichen planus       0.12      0.18      0.15        17
                                    Lichen sclerosus       0.00      0.00      0.00        14
                             Ligneous conjunctivitis       0.00      0.00      0.00        16
                                  Linear IgA disease       1.00      1.00      1.00        18
                                     Lupus nephritis       0.00      0.00      0.00        15
                                    Lupus vasculitis       0.00      0.00      0.00        17
                              Membranous nephropathy       0.00      0.00      0.00        17
                      Microscopic polyangiitis (MPA)       0.00      0.00      0.00        17
                                      Mooren's ulcer       0.00      0.00      0.00        19
                                             Morphea       0.00      0.00      0.00        20
                                  Multiple sclerosis       0.00      0.00      0.00        15
                                   Myasthenia gravis       0.00      0.00      0.00        30
                                            Myositis       0.50      0.06      0.11        17
                                Neuromyelitis optica       0.06      0.07      0.07        14
        Neuromyelitis optica (Devic's disease)/NMOSD       0.00      0.00      0.00        18
                                       Neuromyotonia       0.06      0.17      0.09        12
                                              Normal       0.99      1.00      1.00       500
                       Opsoclonus myoclonus syndrome       0.00      0.00      0.00        19
                                      Optic neuritis       0.00      0.00      0.00        16
                                   Ord's thyroiditis       0.00      0.00      0.00        16
              Paraneoplastic cerebellar degeneration       0.33      0.06      0.11        16
                 Paroxysmal nocturnal hemoglobinuria       0.17      0.07      0.10        15
                                  Pemphigus vulgaris       1.00      1.00      1.00        17
                                   Pernicious anemia       1.00      1.00      1.00        17
                          Polyarteritis nodosa (PAN)       0.08      0.08      0.08        13
                              Polymyalgia rheumatica       0.00      0.00      0.00        16
                                        Polymyositis       0.00      0.00      0.00        18
                           Premature ovarian failure       0.00      0.00      0.00        18
                      Primary sclerosing cholangitis       0.00      0.00      0.00        15
                                           Psoriasis       0.00      0.00      0.00        16
                      Pulmonary alveolar proteinosis       0.25      0.06      0.10        16
                              Restless legs syndrome       0.12      0.06      0.08        17
                             Rheumatic heart disease       0.00      0.00      0.00        13
                                Rheumatoid arthritis       0.00      0.00      0.00        18
                             Rheumatoid lung disease       0.00      0.00      0.00        16
                               Rheumatoid vasculitis       0.50      0.06      0.10        18
                                         Sarcoidosis       0.07      0.06      0.06        17
                                           Scleritis       0.20      0.06      0.09        18
                    Scleroderma (systemic sclerosis)       1.00      1.00      1.00        15
                                    Sjögren syndrome       0.00      0.00      0.00        17
                               Stiff-person syndrome       0.20      0.06      0.10        16
                                    Susac's syndrome       0.00      0.00      0.00        16
                                   Sydenham's chorea       0.08      0.07      0.07        14
                              Sympathetic ophthalmia       0.00      0.00      0.00        15
                        Systemic Lupus Erythematosus       1.00      1.00      1.00        19
                                Takayasu's arteritis       0.00      0.00      0.00        15
                 Thrombotic thrombocytopenic purpura       0.00      0.00      0.00        17
                                Tolosa–Hunt syndrome       0.00      0.00      0.00        16
                                 Transverse myelitis       0.00      0.00      0.00        18
                                  Ulcerative colitis       1.00      1.00      1.00        16
   Undifferentiated connective tissue disease (UCTD)       0.00      0.00      0.00        15
                               Urticarial vasculitis       0.00      0.00      0.00        15
                                          Vasculitis       0.00      0.00      0.00        20
                                            Vitiligo       0.09      0.06      0.07        18

                                            accuracy                           0.36      2500
                                           macro avg       0.23      0.20      0.20      2500
                                        weighted avg       0.38      0.36      0.36      2500

c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ramki\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [28]:
from sklearn.ensemble import RandomForestClassifier
import joblib

# Train final global model on full training data
final_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    class_weight='balanced',
    random_state=42
)

final_model.fit(X_train, y_train)

# Save model
joblib.dump(final_model, "autoimmune.pkl")

print("Autoimmune model saved successfully as autoimmune.pkl!")

Autoimmune model saved successfully as autoimmune.pkl!